name: Build Rust Binaries

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-macos-arm64:
    uses: bbusse/github-workflows/.github/workflows/build-rust.yml@dev
    with:
      binary_name: wi
      artifact_name: wi
      musl: true
